### ISSUE TITLE
Adding Jaccard Distance

### ISSUE THREAD

**Issue by nithinkrishna** [chrismattmann/tika-similarity#55]
Is the jacquard distance metric being developed? If not I'd like to build this.

Whats the workflow for new modules to be added? Do we have a test-suite for this project?

**Comment by nithinkrishna** [comment]
Here is a [PR](https://github.com/chrismattmann/tika-similarity/pull/56) for the same.

**Comment by harsham05** [comment]
Absolute Jaccard Distance is already present in tika-similarity from the beginning.
See my comments in your [PR](https://github.com/chrismattmann/tika-similarity/pull/56)

Closing this @chrismattmann
