### ISSUE TITLE
handle empty metadata in files for edit distance

### ISSUE THREAD

**Issue by aishwarya-parameshwaran** [chrismattmann/tika-similarity#57]
For files with no metadata, edit-value-similarity.py raises a KeyError exception on line no. 59. I temporarily handled it on my local machine as shown below:

```python
    try:
        intersect_features = set(file1_parsedData["metadata"].keys()) & set(file2_parsedData["metadata"].keys()) 
    except KeyError, e:
        continue
```

Should I submit a pull request to fix this?

**Comment by harsham05** [comment]
@aishwarya-parameshwaran Thats odd. Its handled in below lines
```
filename_list = [filename for filename in filename_list if parser.from_file(filename)]
if acceptTypes:
            filename_list = [filename for filename in filename_list if str(parser.from_file(filename)['metadata']['Content-Type'].encode('utf-8')).split('/')[-1] in acceptTypes]
else:
            print "Accepting all MIME Types....."
```

**Comment by harsham05** [comment]
@aishwarya-parameshwaran I would prefer a fix in lines 45-49. Can you please attach here the file you encountered where no metadata was extracted by tika server?

**Comment by harsham05** [comment]
@aishwarya-parameshwaran I would prefer a fix at line 45. Can you please attach here the file you encountered where no metadata was extracted? Thanks

**Comment by aishwarya-parameshwaran** [comment]
@harsham05  I am unable to attach the file since it has absolutely no content or metadata. I'll try and shift the fix to line 45. Thanks.

**Comment by harsham05** [comment]
Fixed in https://github.com/chrismattmann/tika-similarity/pull/59
