### ISSUE TITLE
Is Solr Similarity ready yet?

### ISSUE THREAD

**Issue by chrismattmann** [chrismattmann/tika-similarity#64]
cc @harsham05

**Comment by harsham05** [comment]
@chrismattmann Do you mean this? I used it to enrich Weapons Solr Core
https://github.com/harsham05/new590DR

**Comment by harsham05** [comment]
@chrismattmann Based on the requirement 
1. Visualize a JSON dump ( from a Solr query) and generate similarity-scores.txt for Jaccard, Edit, Cosine Distances.
This is already done. Will send PR with minor code Refactor, since Solr-similarity was implemented with ImageCat Ingestion in mind.

**Comment by chrismattmann** [comment]
great send PR thanks @harsham05

**Comment by harsham05** [comment]
@chrismattmann  Jaccard Solr Similarity is done
https://github.com/harsham05/Solr-ES-Similarity
<img width="1920" alt="screen shot 2016-04-08 at 3 55 10 am" src="https://cloud.githubusercontent.com/assets/8755540/14381811/0e68c5dc-fd3e-11e5-9fcd-54127a2895cd.png">

**Comment by chrismattmann** [comment]
that is AWESOME, @harsham05 . This needs to be brought into tika-similarity..

**Comment by harsham05** [comment]
Fixed in https://github.com/chrismattmann/tika-similarity/pull/79
